project:
  type: website
  output-dir: docs

website:
  title: "Home"
  #favicon: logo.png
  navbar:
    left:
      - href: about.qmd
        text: About
      - href: research/index.qmd
        text: Research
      - href: research/index_publ.qmd
        text: Publications
      - href: research/index_teach.qmd
        text: Teaching
      - href: cv_new.pdf
        text: CV

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor:
  render-on-save: true
